services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: yomistream-backend:local
    container_name: yomistream-backend
    environment:
      - PORT=8001
    env_file:
      - ./Backend/.env
    expose:
      - "8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webnet


  nginx:
      build: ./nginx
      container_name: yomistream-nginx
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        backend:
          condition: service_healthy

networks:
  webnet:
    driver: bridge
